assert_ok: Remove `Debug` requirement for `Ok()` content (#3)
The `has_private_in_public_issue` cfg is used to get around "error[E0453]: allow(private_in_public) overruled by outer forbid(private_in_public)" errors on the Rust v1.15 CI job that we haven't found another way of solving.